### ISSUE TITLE
Voice Command - Google Automation

### ISSUE THREAD

**Issue by toddvarriano** [Mellit7/Smartthings-SqueezeBox-Control#1]
Thank you for your creating this code.  This is great.  I am just having an issue that I don't necessarily see in the documentation.  If you can assist, that would be great.

First, I am unsure of how to get the commands to work with Google Assistant.  I have installed the SmartApp, assigned to a device, and mapped a couple of buttons for testing.   The two buttons work with the app.

Second, I do not see how to make any routine or automation other than to change the device status to on/off.  I am new to SmartThings, and am using Classic.  Perhaps that is a limitation of the platform/app.

Third, just curious about the voice option, Salli.  How is that used?  Does it speak back to me?  If so, how.

Most of this is just beginner stuff, and things I am missing.  All players are working.  Thanks again for your development.

Todd

**Comment by toddvarriano** [comment]
OK, I figured out the text to speech, it looks like a matter of just getting the correct SmartApps.  If you have any suggestions for use, please let me know.

Still having issue getting Google Assistant to work correctly.  Any tips would be appreciated.

**Comment by Mellit7** [comment]
My apologies, I didn't realize you had contacted me here.  I monitor the Smartthings forum.

Glad you got the speech thing figured out.

As to Google Assistant.  For voice control of the app, if you used the the SmartApp to map a button named Pause My Player to the pause function, once you have your Google Assistant to Smartthings connection set up and the button selected in the authorization, you simply say

  Ok Google, turn on Pause My Player

or better yet, set up a Google Assistant shortcut to do that with something more friendly like

   Ok Google, pause my player

so that the phrase pause my player turns on your Pause My Player button.

As to automations, yes, the main routine automations only access the On/Off actions.  This is why I have created some button mapping.  Those can be turned on in a routine, which will then cause the mapped action to happen. So with the SmartApp, you can turn on buttons to control play/pause/stop and the three button presets.

For more complicated items like speak, you will need to use a SmartApp or WebCore.  Those are beyond my ability to help you with here, but lots of info on the Smartthings forums.

If you do get into the more advanced things like SmartApps/WebCore, you can make your player talk to you by using the speak(msg) command where msg is a string containing the message you want spoken, like "Hello, how are you?"

Forgot to mention, if you want a simple way of getting thinks speaking, look at Big Talker 2.  It will handle setting up speech for you based on many Smartthings events.  This code works with both types of devices in Bit Talker 2

**Comment by toddvarriano** [comment]
Thanks for the reply and the info on button mapping, I didn’t even think of that.  I have been using WebBore as well, so moving right along.  Thanks again for posting your code.

Todd
